io:
  input_dir: "data/input/same_document"
  output_dir: "data/output/same_document"
status:
  empty_min_fallback: "GLOBAL_MIN"
runtime:
  fail_on_missing_columns: true
  float_na_fill: null
log:
  level: "INFO"
